name: Code Review

on: [push]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint script
        run: python scripts/run_pylint.py

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: reports/pylint_report.txt
